"""empty message

Revision ID: 444aa11f81ab
Revises: 088d9c0013b2
Create Date: 2022-08-20 15:41:14.098874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '444aa11f81ab'
down_revision = '088d9c0013b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contact', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contact', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
